name: simulators
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.23=he99959a_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py39h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - annotated-types==0.7.0
      - argparse==1.4.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - clarabel==0.11.1
      - contourpy==1.3.0
      - cplex==22.1.2.0
      - cryptography==46.0.2
      - cvxpy==1.7.3
      - cycler==0.12.1
      - dill==0.4.0
      - docplex==2.30.251
      - fonttools==4.60.1
      - ibm-cloud-sdk-core==3.24.2
      - ibm-platform-services==0.69.0
      - idna==3.11
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.7
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==2.0.2
      - osqp==1.0.5
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - psutil==7.1.0
      - pycparser==2.23
      - pydantic==2.12.1
      - pydantic-core==2.41.3
      - pydot==4.0.1
      - pyjwt==2.10.1
      - pylatexenc==2.10
      - pyparsing==3.2.5
      - pyspnego==0.12.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - qiskit==2.2.1
      - qiskit-aer==0.17.2
      - qiskit-ibm-runtime==0.42.0
      - qiskit-optimization==0.7.0
      - requests==2.32.5
      - requests-ntlm==1.3.0
      - rustworkx==0.17.1
      - scipy==1.13.1
      - scs==3.2.9
      - seaborn==0.13.2
      - six==1.17.0
      - stevedore==5.5.0
      - sympy==1.14.0
      - typing==3.7.4.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - zipp==3.23.0
prefix: /mnt/netapp1/Store_CESGA/home/cesga/jsouto/conda/envs/simulators
